name: FastAPI Auth Route Test

on:
  push:
    branches: [ main 
  pull_request:
    branches: [ main ]  

jobs:
  test-auth-route:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r API_CONTENEUR/Conteneur_BDD_utilisateur/requirements.txt

    - name: Run Auth Tests
      run: pytest API_CONTENEUR/Conteneur_BDD_utilisateur/authentification_test.py
